#!/bin/sh
singularity run --app R \
    --bind /tmp:/tmp \
    --bind /usr/share/fonts/:/usr/share/fonts/ \
    --bind /usr/share/fonts:/usr/share/fonts \
    --bind /data \
    ~/fishing-tools/NU_Quest/quest_dev_debian.sif "$@"
    # ~/fishing-tools/NU_Quest/quest_dev_rocky.sif "$@"
